
name: internship
description: "Edutech"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  get: 4.6.5
  get_storage: ^2.0.3
  flutter_native_splash: ^2.3.0
  lottie: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/gungsatria/
    - assets/gungsatria/images/
    - assets/gungsatria/icons/
    - assets/krisna/
    - assets/krisna/images/
    - assets/krisna/icons/

  fonts:
    - family: VisibyRoundHeavy
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-Heavy.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-HeavyOblique.ttf
          style: italic
    - family: VisibyRoundExtraBold
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-ExtraBold.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-ExtraBoldOblique.ttf
          style: italic
    - family: VisibyRoundBold
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-Bold.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-BoldOblique.ttf
          style: italic
    - family: VisibyRoundDemiBold
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-DemiBold.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-DemiBoldOblique.ttf
          style: italic
    - family: VisibyRoundMedium
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-Medium.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-MediumOblique.ttf
          style: italic
    - family: VisibyRoundRegular
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-Regular.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-Oblique.ttf
          style: italic
    - family: VisibyRoundLight
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-Light.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-LightOblique.ttf
          style: italic
    - family: VisibyRoundExtraLight
      fonts:
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-ExtraLight.ttf
          style: normal
        - asset: assets/fonts/VisibyRound/VisbyRoundCF-ExtraLightOblique.ttf
          style: italic
